name: preview
on:
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup EXPO
        uses: expo/expo-github-action@v7
        with:
          expo-version: 7.4.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build on EAS for staging
        run: npx eas build --profile staging --platform android --non-interactive --no-wait